### ISSUE TITLE
No scrollbar in both editors under Firefox

### ISSUE THREAD

**Issue by petersmith-hun** [gabemiller/calmdown#1]
Hi @gabemiller ,

First of all, Calmdown is a really nice markdown editor - keep up the good work! ;)
I've given it a try, using Firefox and it seems that there's no scrollbar if the content is too long in markdown editor, and in the translated HTML view as well. Could you please check it?

**Comment by gabemiller** [comment]
Hello @petersmith-hun 
Thank you for your notice and good review about my project. I've already fixed the scrollbar issue. If you have time. please check it yourself.

**Comment by petersmith-hun** [comment]
Hi @gabemiller ,

I've checked it and it is fine now - thank you!
