### ISSUE TITLE
Text color in editor (to work in dark themes)

### ISSUE THREAD

**Issue by xrat** [gabemiller/calmdown#12]
I only had a quick look at **calmdown** so far, however, I am very happy I found this nice editor! Thanks a lot! I am looking forward to using it thoroughly :)

I use dark themes (white-on-black) for my O/S. In the editor (textarea.cd-editor) `background-color` is set but `color` is not. It ends up as light grey on white on my computers.

I am sorry I am not a programmer, so I cannot contribute code. All the more, I am grateful for yours.

**Comment by gabemiller** [comment]
Thank you for your respone. I am glad that you find this tiny editor useful. In the following days I'll try to create a new dark theme for calmdown and enhance the code little so it can be used more easily.

**Comment by xrat** [comment]
@gabemiller The dark theme looks great, thanks a lot. In the light theme text color is still not set, so I get an unreadable light gray on white background due to the theme of my O/S.

**Comment by gabemiller** [comment]
@xrat Thank you for your bug report. You can now download version 0.5.10, in which this bug is fixed.
https://github.com/gabemiller/calmdown/issues/16

**Comment by xrat** [comment]
Thanks a lot. I used the new release 0.5.10, also had a much closer look in general: Works very well!
