### ISSUE TITLE
What are  optional configuration ?

### ISSUE THREAD

**Issue by k0fi** [gabemiller/calmdown#24]
I have imported `calmdown.min.css` and `calmdown.min.js` and then in my global.js I added:

`const cd = new Calmdown({
    // optional configuration
   });`

And also `<div class="calmdown"></div> ` on my html page. 

The toolbar appears only with a question mark. When it is hovered it shows `Press Ctrl+h`. 
There is no indication in the docs on what are the configuration options. 
So wondering how can I shows a proper toolbar with usual edit buttons?

**Comment by gabemiller** [comment]
Hi @k0fi,
Thank you for using calmdown. You should check this [config file](https://github.com/gabemiller/calmdown/blob/master/src/js/Config.js). In this file there are the default configuration options which can be overwritten easily by the given parameter object in Calmdown constructor. I hope this answer helped you. If you have any other questions, just ask me.

**Comment by xrat** [comment]
@gabemiller There was a typo in your message. 
@k0fi He meant https://github.com/gabemiller/calmdown/blob/master/src/js/Config.js

**Comment by gabemiller** [comment]
@xrat thank you :)
